services:
  db:
    container_name: sql-puzzle
    build: ./
    image: mysql_ja:8.0-debian
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: puzzle
      MYSQL_DATABASE: puzzle
      MYSQL_USER: puzzle
      MYSQL_PASSWORD: puzzle
      MYSQL_PORT: 3306
      LANG: ja_JP.UTF-8
    cap_add:
      - SYS_NICE
    volumes:
      - sql-puzzle:/var/lib/mysql

volumes:
  sql-puzzle:
